version: '3.9'

services:

  nginx:
    build: ./dockers/nginx
    volumes_from:
      - volumes_source
      - webapp
      - volumes_data
    volumes:
      - ./dockers/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockers/etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - "${HTTPPORT}:80"
    links:
       - webapp:phpfpm


  webapp:
      build: ./dockers/webapp
      expose:
        - 9000
      links:
        - db
      environment:
        - WORDPRESS_DB_PASSWORD=root
        - WORDPRESS_DB_HOST:mysql
      volumes_from:
        - volumes_source
        - volumes_data
      # volumes:
      #   - ./dockers/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf

   
  memcached:
    image: memcached
    
  db:
      image: mariadb:10.2
      #command: --max_allowed_packet=33554432      # Set max_allowed_packet to 32M (or any other value)

      volumes_from:
        - volumes_data
      environment:
        - MYSQL_ROOT_PASSWORD=rojtf15
        - MYSQL_PASSWORD=cal214m
        - MYSQL_DATABASE=climalife_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions
### Sources directory ##############@
  volumes_source:
    image: tianon/true
    volumes:
      - ./:/var/www/html


### Databases Data Container ################################

  volumes_data:
      image: tianon/true
      volumes:
          - ./dockers/volumes/mysql:/var/lib/mysql

### Add more Containers below ###############################